export const activities = [
  {
    id: 'movie',
    name: 'Movie Night',
    emoji: '🎬',
    description: 'Catch the latest blockbuster or a cult classic together.',
    image: 'https://images.pexels.com/photos/7991258/pexels-photo-7991258.jpeg?auto=compress&cs=tinysrgb&h=400&w=600',
  },
  {
    id: 'coffee',
    name: 'Coffee & Conversations',
    emoji: '☕',
    description: 'Flat whites, filter coffee, and no awkward silences.',
    image: 'https://images.pexels.com/photos/5709521/pexels-photo-5709521.jpeg?auto=compress&cs=tinysrgb&h=400&w=600',
  },
  {
    id: 'shopping',
    name: 'Shopping',
    emoji: '🛍️',
    description: 'A second opinion that actually has taste.',
    image: 'https://images.pexels.com/photos/7155936/pexels-photo-7155936.jpeg?auto=compress&cs=tinysrgb&h=400&w=600',
  },
  {
    id: 'dining',
    name: 'Lunch / Dinner',
    emoji: '🍽️',
    description: 'Good food, better company, zero solo-table awkwardness.',
    image: 'https://images.pexels.com/photos/8921578/pexels-photo-8921578.jpeg?auto=compress&cs=tinysrgb&h=400&w=600',
  },
  {
    id: 'events',
    name: 'Events',
    emoji: '🎉',
    description: 'Concerts, festivals, and everything worth showing up for.',
    image: 'https://images.pexels.com/photos/14364670/pexels-photo-14364670.jpeg?auto=compress&cs=tinysrgb&h=400&w=600',
  },
  {
    id: 'explore-city',
    name: 'Explore the City',
    emoji: '🚶',
    description: 'Wander streets, find cafes, and play tourist in your own city.',
    image: 'https://images.pexels.com/photos/4881146/pexels-photo-4881146.jpeg?auto=compress&cs=tinysrgb&h=400&w=600',
  },
  {
    id: 'gaming',
    name: 'Gaming',
    emoji: '🎮',
    description: 'Co-op, competitive, or just chilling on the couch.',
    image: 'https://images.pexels.com/photos/9068963/pexels-photo-9068963.jpeg?auto=compress&cs=tinysrgb&h=400&w=600',
  },
  {
    id: 'sports',
    name: 'Play Something',
    emoji: '🏸',
    description: 'Badminton, tennis, table tennis — pick your racket.',
    image: 'https://images.pexels.com/photos/8007500/pexels-photo-8007500.jpeg?auto=compress&cs=tinysrgb&h=400&w=600',
  },
  {
    id: 'social',
    name: 'Social Events',
    emoji: '📸',
    description: 'Parties, meetups, and gatherings where you need a plus-one.',
    image: 'https://images.pexels.com/photos/6405799/pexels-photo-6405799.jpeg?auto=compress&cs=tinysrgb&h=400&w=600',
  },
];

export const buddies = [
  {
    id: 'aarav',
    name: 'Aarav',
    age: 24,
    tagline: 'Coffee enthusiast, movie lover & terrible at bowling.',
    image: 'https://images.pexels.com/photos/6338266/pexels-photo-6338266.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
    gallery: [
      'https://images.pexels.com/photos/6338266/pexels-photo-6338266.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
      'https://images.pexels.com/photos/6102858/pexels-photo-6102858.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
      'https://images.pexels.com/photos/9817252/pexels-photo-9817252.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
    ],
    rating: 4.9,
    outings: 87,
    pricePerHour: 499,
    location: 'Lucknow',
    interests: ['Coffee', 'Movies', 'Gaming', 'Street Food'],
    activities: ['movie', 'coffee', 'gaming', 'dining'],
    verified: true,
    available: true,
    about: "I'm the person who actually shows up on time. Big into indie films, filter coffee, and finding the best momo stalls in the city. I talk a lot about movies but I'm a great listener too. If you need someone to make a plan feel effortless, that's kind of my thing.",
    languages: ['Hindi', 'English', 'Awadhi'],
    availability: ['Weekdays after 5 PM', 'Weekends anytime'],
    responseTime: 'Usually replies in 30 minutes',
    reviews: [
      { id: 'r1', author: 'Priya', rating: 5, text: 'Really easy to talk to and the movie plan was super smooth. He picked a great theatre and even knew where to get the best popcorn.', activity: 'Movie Night', date: '2 weeks ago' },
      { id: 'r2', author: 'Rohan', rating: 5, text: 'Booked Aarav for a coffee meetup before a job interview. He calmed my nerves completely. genuinely good conversation.', activity: 'Coffee & Conversations', date: '1 month ago' },
      { id: 'r3', author: 'Sneha', rating: 4, text: 'Fun gaming session! He let me win the first round (I think) and then absolutely destroyed me. Great sport.', activity: 'Gaming', date: '1 month ago' },
    ],
  },
  {
    id: 'priya',
    name: 'Priya',
    age: 23,
    tagline: 'Knows every hidden cafe in the city. Will judge your coffee order.',
    image: 'https://images.pexels.com/photos/8720868/pexels-photo-8720868.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
    gallery: [
      'https://images.pexels.com/photos/8720868/pexels-photo-8720868.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
      'https://images.pexels.com/photos/36918310/pexels-photo-36918310.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
      'https://images.pexels.com/photos/10210852/pexels-photo-10210852.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
    ],
    rating: 5.0,
    outings: 112,
    pricePerHour: 599,
    location: 'Mumbai',
    interests: ['Coffee', 'Shopping', 'Events', 'Photography'],
    activities: ['coffee', 'shopping', 'events', 'social'],
    verified: true,
    available: true,
    about: "I've been exploring Mumbai's cafe scene since I was 16. I know the city like the back of my hand and I love showing people around. Whether it's a weekend market, a pop-up event, or just finding the perfect flat white — I'm your person.",
    languages: ['Hindi', 'English', 'Marathi'],
    availability: ['Weekends', 'Friday evenings'],
    responseTime: 'Usually replies in 15 minutes',
    reviews: [
      { id: 'r1', author: 'Karan', rating: 5, text: 'Priya took me to a cafe I never knew existed. Best cold brew of my life. She knows this city inside out.', activity: 'Coffee & Conversations', date: '1 week ago' },
      { id: 'r2', author: 'Ananya', rating: 5, text: 'Went shopping with Priya and she honestly has better taste than me. Found things I never would have picked up myself.', activity: 'Shopping', date: '3 weeks ago' },
      { id: 'r3', author: 'Vikram', rating: 5, text: 'Booked her for a music festival. She made the whole experience so much more fun. Zero awkwardness.', activity: 'Events', date: '1 month ago' },
    ],
  },
  {
    id: 'rohan',
    name: 'Rohan',
    age: 26,
    tagline: 'Gym rat, foodie, and surprisingly good at karaoke.',
    image: 'https://images.pexels.com/photos/2590287/pexels-photo-2590287.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
    gallery: [
      'https://images.pexels.com/photos/2590287/pexels-photo-2590287.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
      'https://images.pexels.com/photos/6502290/pexels-photo-6502290.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
      'https://images.pexels.com/photos/6200777/pexels-photo-6200777.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
    ],
    rating: 4.8,
    outings: 64,
    pricePerHour: 449,
    location: 'Delhi',
    interests: ['Dining', 'Sports', 'Events', 'Fitness'],
    activities: ['dining', 'sports', 'events', 'explore-city'],
    verified: true,
    available: true,
    about: "Delhi-born, food-obsessed, and always up for an adventure. I know the best biryani spots in Old Delhi and the best cocktails in Hauz Khas. If you want someone who can match your energy, I'm your guy.",
    languages: ['Hindi', 'English', 'Punjabi'],
    availability: ['Weekday evenings', 'Weekends'],
    responseTime: 'Usually replies in 45 minutes',
    reviews: [
      { id: 'r1', author: 'Meera', rating: 5, text: 'Rohan took me on a street food crawl in Old Delhi. I ate way too much and regretted nothing. Best evening in months.', activity: 'Lunch / Dinner', date: '2 weeks ago' },
      { id: 'r2', author: 'Arjun', rating: 4, text: 'Solid badminton session. He actually plays well so be ready for a real game.', activity: 'Play Something', date: '3 weeks ago' },
    ],
  },
  {
    id: 'sneha',
    name: 'Sneha',
    age: 25,
    tagline: 'Art gallery hopper. Will find the aesthetic in everything.',
    image: 'https://images.pexels.com/photos/20132403/pexels-photo-20132403.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
    gallery: [
      'https://images.pexels.com/photos/20132403/pexels-photo-20132403.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
      'https://images.pexels.com/photos/7485047/pexels-photo-7485047.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
      'https://images.pexels.com/photos/36152386/pexels-photo-36152386.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
    ],
    rating: 4.9,
    outings: 93,
    pricePerHour: 549,
    location: 'Bangalore',
    interests: ['Events', 'Coffee', 'Photography', 'Art'],
    activities: ['events', 'coffee', 'social', 'explore-city'],
    verified: true,
    available: true,
    about: "I live for weekend art markets, indie music gigs, and long walks in Cubbon Park. I'm the friend who always has a plan and somehow gets everyone to show up. Let's explore Bangalore together.",
    languages: ['Hindi', 'English', 'Kannada'],
    availability: ['Weekends', 'Thursday evenings'],
    responseTime: 'Usually replies in 20 minutes',
    reviews: [
      { id: 'r1', author: 'Aditya', rating: 5, text: 'Sneha took me to an art gallery I walked past a hundred times and never noticed. Completely changed my perspective.', activity: 'Events', date: '1 week ago' },
      { id: 'r2', author: 'Ishita', rating: 5, text: 'Booked Sneha for a social event where I knew no one. She made me feel comfortable instantly. Such a warm person.', activity: 'Social Events', date: '2 weeks ago' },
      { id: 'r3', author: 'Kabir', rating: 5, text: 'Coffee turned into a 3-hour conversation about everything. Time just flew.', activity: 'Coffee & Conversations', date: '1 month ago' },
    ],
  },
  {
    id: 'vikram',
    name: 'Vikram',
    age: 28,
    tagline: 'Will beat you at FIFA and then buy you dinner to make up for it.',
    image: 'https://images.pexels.com/photos/6102858/pexels-photo-6102858.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
    gallery: [
      'https://images.pexels.com/photos/6102858/pexels-photo-6102858.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
      'https://images.pexels.com/photos/6338266/pexels-photo-6338266.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
      'https://images.pexels.com/photos/29153201/pexels-photo-29153201.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
    ],
    rating: 4.7,
    outings: 51,
    pricePerHour: 399,
    location: 'Pune',
    interests: ['Gaming', 'Dining', 'Movies'],
    activities: ['gaming', 'dining', 'movie'],
    verified: true,
    available: false,
    about: "Software engineer by day, FIFA pro by night. I'm laid-back, easy to talk to, and I know every good burger spot in Pune. If you want a chill evening with zero pressure, let's hang.",
    languages: ['Hindi', 'English'],
    availability: ['Weekends only'],
    responseTime: 'Usually replies in 1 hour',
    reviews: [
      { id: 'r1', author: 'Tanvi', rating: 5, text: 'Gaming night was so fun. He brought snacks and everything. Felt like hanging out with an old friend.', activity: 'Gaming', date: '2 weeks ago' },
      { id: 'r2', author: 'Nikhil', rating: 4, text: 'Good burger, good conversation. He knows his stuff when it comes to food in Pune.', activity: 'Lunch / Dinner', date: '3 weeks ago' },
    ],
  },
  {
    id: 'ananya',
    name: 'Ananya',
    age: 22,
    tagline: "Professional window shopper. Will find deals you didn't know existed.",
    image: 'https://images.pexels.com/photos/36918310/pexels-photo-36918310.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
    gallery: [
      'https://images.pexels.com/photos/36918310/pexels-photo-36918310.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
      'https://images.pexels.com/photos/8720868/pexels-photo-8720868.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
      'https://images.pexels.com/photos/17827869/pexels-photo-17827869.jpeg?auto=compress&cs=tinysrgb&h=800&w=600',
    ],
    rating: 4.9,
    outings: 78,
    pricePerHour: 499,
    location: 'Hyderabad',
    interests: ['Shopping', 'Coffee', 'Events', 'Movies'],
    activities: ['shopping', 'coffee', 'events', 'movie'],
    verified: true,
    available: true,
    about: "I have a sixth sense for sales and a talent for making shopping fun (not exhausting). I know every mall in Hyderabad and which stores have the best stuff. Let's find you something great.",
    languages: ['Hindi', 'English', 'Telugu'],
    availability: ['Weekends', 'Wednesday evenings'],
    responseTime: 'Usually replies in 25 minutes',
    reviews: [
      { id: 'r1', author: 'Riya', rating: 5, text: 'Ananya helped me find a wedding outfit in 2 hours that I spent 3 weeks looking for. She is a genius.', activity: 'Shopping', date: '1 week ago' },
      { id: 'r2', author: 'Dev', rating: 5, text: 'She turned a boring Saturday into a genuinely fun day out. Great energy and even better taste.', activity: 'Explore the City', date: '2 weeks ago' },
    ],
  },
];

export const sampleBookings = [
  {
    id: 'b1',
    buddyId: 'aarav',
    buddyName: 'Aarav',
    buddyImage: 'https://images.pexels.com/photos/6338266/pexels-photo-6338266.jpeg?auto=compress&cs=tinysrgb&h=200&w=200',
    activity: 'Movie Night',
    date: 'Saturday, Sep 7',
    time: '7:00 PM',
    duration: 3,
    location: 'PVR Phoenix, Lucknow',
    buddyFee: 1497,
    hangoFee: 149,
    total: 1646,
    status: 'upcoming',
  },
  {
    id: 'b2',
    buddyId: 'priya',
    buddyName: 'Priya',
    buddyImage: 'https://images.pexels.com/photos/8720868/pexels-photo-8720868.jpeg?auto=compress&cs=tinysrgb&h=200&w=200',
    activity: 'Coffee & Conversations',
    date: 'Sunday, Aug 25',
    time: '11:00 AM',
    duration: 2,
    location: 'Blue Tokai, Bandra',
    buddyFee: 1198,
    hangoFee: 119,
    total: 1317,
    status: 'completed',
  },
  {
    id: 'b3',
    buddyId: 'sneha',
    buddyName: 'Sneha',
    buddyImage: 'https://images.pexels.com/photos/20132403/pexels-photo-20132403.jpeg?auto=compress&cs=tinysrgb&h=200&w=200',
    activity: 'Events',
    date: 'Saturday, Aug 17',
    time: '4:00 PM',
    duration: 4,
    location: 'Phoenix Marketcity, Bangalore',
    buddyFee: 2196,
    hangoFee: 219,
    total: 2415,
    status: 'completed',
  },
];

export const sampleConversations = [
  {
    id: 'c1',
    buddyId: 'aarav',
    buddyName: 'Aarav',
    buddyImage: 'https://images.pexels.com/photos/6338266/pexels-photo-6338266.jpeg?auto=compress&cs=tinysrgb&h=200&w=200',
    online: true,
    lastMessage: 'Looking forward to Saturday! I know a great spot for dinner before the movie.',
    lastTime: '12 min ago',
    bookingContext: 'Movie · Saturday 7 PM',
    messages: [
      { id: 'm1', sender: 'me', text: 'Hey Aarav! Excited for the movie this Saturday!', time: '2:30 PM', type: 'text' },
      { id: 'm2', sender: 'buddy', text: "Hey! Same here. I was thinking we could grab dinner before? There's a great place right next to PVR Phoenix.", time: '2:32 PM', type: 'text' },
      { id: 'm3', sender: 'me', text: 'That sounds perfect. What time should we meet?', time: '2:33 PM', type: 'text' },
      { id: 'm4', sender: 'buddy', text: 'How about 5:30? Gives us time for a relaxed dinner before the 7 PM show.', time: '2:35 PM', type: 'text' },
      { id: 'm5', sender: 'me', text: 'Works for me!', time: '2:36 PM', type: 'text' },
      { id: 'm6', sender: 'buddy', text: 'Looking forward to Saturday! I know a great spot for dinner before the movie.', time: '2:37 PM', type: 'text' },
    ],
  },
  {
    id: 'c2',
    buddyId: 'priya',
    buddyName: 'Priya',
    buddyImage: 'https://images.pexels.com/photos/8720868/pexels-photo-8720868.jpeg?auto=compress&cs=tinysrgb&h=200&w=200',
    online: false,
    lastMessage: 'Thanks for the coffee! Let me know when you want to explore South Mumbai next.',
    lastTime: '2 days ago',
    bookingContext: 'Coffee · Aug 25',
    messages: [
      { id: 'm1', sender: 'buddy', text: 'Hey! See you at Blue Tokai at 11?', time: '10:45 AM', type: 'text' },
      { id: 'm2', sender: 'me', text: 'On my way!', time: '10:50 AM', type: 'text' },
      { id: 'm3', sender: 'buddy', text: 'Thanks for the coffee! Let me know when you want to explore South Mumbai next.', time: '1:15 PM', type: 'text' },
    ],
  },
];

export const cities = [
  'Lucknow',
  'Mumbai',
  'Delhi',
  'Bangalore',
  'Pune',
  'Hyderabad',
  'Chennai',
  'Kolkata',
  'Jaipur',
  'Ahmedabad',
];